apiVersion: v1
kind: Service
metadata:
  name: app-fakenews-flask
  namespace: fakenews
  labels:
    application: app-fakenews-flask
spec:
  type: LoadBalancer
  selector:
    app: app-fakenews-flask
    application: app-fakenews-flask
  ports:
    - port: 5000
      targetPort: 5000

